#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1

# #######################################
REPO=vim-session
FILE=session.vim
LOCAL=""
while getopts "l" arg
do
	case $arg in
            l) LOCAL="yes" ;;
        esac
done
ANON=`date`
print $ANON
print "Local Deployment..."
cp plugin/$FILE /home/mestes/.vim/bundle/$REPO/plugin/$FILE
cp tools/vit ~/firstbin/vit
cp tools/vi  ~/firstbin/vi
cp ~/.vimrc   tools/.vimrc 

if [ "$PUSHITLOCAL" == "LOCAL" ] ; then
     LOCAL="LOCAL"
fi

print "Building README.md"

print "# vim-session" > README.md
print "Simple Vim session management" >> README.md
print "" >> README.md

print "## Screen Shot" >> README.md
print  "![alt text](https://github.com/archernar/vim-session/blob/master/images/session.png \"Session.vim\")" >> README.md
print "" >> README.md

print "## session.vim" >> README.md
cat plugin/session.vim | gawk '{print "    " $0}' | markdown >> README.md

print "## Example Integration:  vit (Adv. model)" >> README.md
print "" >> README.md
cat tools/vit | gawk '{print "    " $0}' >> README.md

print "## Example Integration: vi (simple model)" >> README.md
print "" >> README.md
cat tools/vi | gawk '{print "    " $0}' >> README.md




if [ "$LOCAL" == "" ] ; then
     IP=192.168.1.1
     fping -c1 -t300 $IP 2>/dev/null 1>/dev/null
     if [ $? -eq 0 ] ; then
          git add plugin/$FILE
          git add tools/vit
          git add tools/vi
          git add tools/.vimrc
          git add images/session.png
          git add pushit
          git add README.md
          git commit -m "Update"
          git push -u origin master
     fi
fi

