#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1



# cp plugin/session.vim   /home/mestes/.vim/bundle/vim-dir/plugin/session.vim
# exit 0



#-------------------------------------------------------------------------------------
./buildmd > README.md
git add plugin/session.vim
git add images/session.png
git add pushit
git add buildmd
git add classmethodlist
git add README.md
git commit -m "Update"
git push -u origin master



git commit -m "Update"
git push -u origin master
REPO=vim-session
rm -rf $HOME/.vim/bundle/$REPO
vim  -c ":PluginInstall! $REPO" -c ":qa!"
#-------------------------------------------------------------------------------------

