#!/bin/bash
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1



HOST=`hostname -s`
EPOCHTIME=`date --rfc-3339=seconds |gawk '{sz= $1 "." $2;gsub(/(:)|(-)|([.])/,"", sz);   print sz}'`
RANDNAME=${HOST}_${EPOCHTIME}


print() {
    echo "$1"
}

if [ "$VIMSPLIT" == "" ]; then 
    export VIMSPLIT=.vimsplit
fi
if [ "$VIMTAB" == "" ]; then 
    export VIMTAB=.vimtab
fi
while getopts "xACDRSKGnabcerstohm:" arg
do
	case $arg in
             s) touch "$VIMSPLIT"
                rm -rf "$VIMTAB"
                exit 0
                ;;
             t) touch "$VIMTAB"
                rm -rf "$VIMSPLIT"
#                vim -c "call LoadSession()"
                exit 0
                ;;
             o) rm -rf "$VIMSPLIT"
                rm -rf "$VIMTAB"
#                vim -c "call LoadSession()"
                exit 0
                ;;
             n) rm -rf "$VIMTAB"
                if [ -a "$VIMSPLIT" ] ; then
                     rm -rf "$VIMSPLIT"
                     print "no splits"
                else
                     touch "$VIMSPLIT"
                     print "splits"
                fi
                exit 0
                ;;
            x) vim -c "call LoadSession()"
               exit 0
               ;;
            a) export VIMSPLITCMDS="vsplit"
               rm -rf "$VIMTAB";echo "vsplit" > "$VIMSPLIT"
               exit 0
               ;;
            b) export VIMSPLITCMDS="split";
               rm -rf "$VIMTAB";echo "split" > "$VIMSPLIT"
               exit 0
               ;;
            c) export VIMSPLITCMDS="split | split"
               rm -rf "$VIMTAB";echo "split | split" > "$VIMSPLIT"
               exit 0
               ;;
            C) vi -c CODE
               exit 0
               ;;
            S) 
               export VIMSELECTEDDIR=~/.vim/Snips 
               vi -c DIRE
               exit 0
               ;;
            D) vi -c DIR
               exit 0
               ;;
            A) vi $RANDNAME -c AWK
               exit 0
               ;;
            G) vi $RANDNAME -c AWK
               exit 0
               ;;
            K) vi $RANDNAME -c KSH
               exit 0
               ;;
            R) vi $RANDNAME
               exit 0
               ;;
            r) rm -f $VIMSESSION
               rm -f $VIMWINDOW
               rm -f $VIMLAYOUT
               rm -f $VIMSPLIT
               exit 0
               ;;
            m) vim -c MRU
               exit 0
               ;;
            e) vim  $VIMSESSION $VIMWINDOW
               exit 0
               ;;
            h) print "vit"
               print "  -D      open with pwd directory pane"
               print "  -S      open with snips directory pane"
               print "  -R      open random name file"
               print "  -K      open KSH snip file"
               print "  -A, -G  open AWK snip file"
               print "  -a      side/side window layout"
               print "  -b      up/down window layout"
               print "  -c      up/mid/down window layout"
               print "  -e      Edit ./.vimsession ./.vimwindows"
               print "  -m      Simple Mode with MRU"
               print "  -n      Toggle no-splits flag"
               print "  -h      Help"
               print "  -r      Remove ./.vimsession and ./.vimwindows"
               print "  -s      Simple Mode:Open in a single window"
               print "  -t      Only Windows Mode: Just open blank windows"
               print ""
               exit 0
               ;;
	esac
done

shift $(($OPTIND - 1))

if [ $# -eq 0 ]; then
          if [ "$VIMSPLIT" == "" ]; then 
              export VIMSPLIT=.vimsplit
          fi
          vim -c "call LoadSession()"
else
    vim $1 $2 $3 $4
fi

