#!/bin/bash
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1



HOST=`hostname -s`
EPOCHTIME=`date --rfc-3339=seconds |gawk '{sz= $1 "." $2;gsub(/(:)|(-)|([.])/,"", sz);   print sz}'`
RANDNAME=${HOST}_${EPOCHTIME}


print() {
    echo "$1"
}

while getopts "ACDRSKGnfabcersthmx:" arg
do
	case $arg in
             n) if [ "$VIMNOSPLITS" == "" ]; then 
                    export VIMNOSPLITS=.vimnosplits
                fi
                if [ -a "$VIMNOSPLITS" ] ; then
                     rm -rf "$VIMNOSPLITS"
                     print "splits"
                else
                     touch "$VIMNOSPLITS"
                     print "no splits"
                fi


                if [ "$VIMSPLIT" == "" ]; then 
                    export VIMSPLIT=.vimsplit
                fi
                if [ -a "$VIMSPLIT" ] ; then
                     rm -rf "$VIMSPLIT"
                     print "no splits"
                else
                     touch "$VIMSPLIT"
                     print "splits"
                fi
                exit 0
                ;;
            f) cp "$VIMSESSION" "$VIMWINDOWS"
               vim -c "call LoadSessionT('$VIMSESSION','$VIMSESSION','e','')"
               exit 0
               ;;
            a) vim -c "call LoadSessionT('$VIMSESSION','$VIMWINDOWS','e','vsplit')"
               exit 0
               ;;
            b) vim -c "call LoadSessionT('$VIMSESSION','$VIMWINDOWS','e','split')"
               exit 0
               ;;
            c) vim -c "call LoadSessionT('$VIMSESSION','$VIMWINDOWS','e','split | split')"
               exit 0
               ;;
            C) vi -c CODE
               exit 0
               ;;
            S) 
               export VIMSELECTEDDIR=~/.vim/Snips 
               vi -c DIRE
               exit 0
               ;;
            D) vi -c DIR
               exit 0
               ;;
            A) vi $RANDNAME -c AWK
               exit 0
               ;;
            G) vi $RANDNAME -c AWK
               exit 0
               ;;
            K) vi $RANDNAME -c KSH
               exit 0
               ;;
            R) vi $RANDNAME
               exit 0
               ;;
            r) rm -f $VIMSESSION
               rm -f $VIMWINDOWS
               rm -f $VIMLAYOUT
               exit 0
               ;;
            s) vim -c "call LoadSession('$VIMSESSION','e')"
               exit 0
               ;;
            x) 
                        case $OPTARG in
                            a) vim -c "call LoadSessionT('$VIMSESSION','$VIMWINDOWS','e','vsplit')"
                               ;;
                            b) vim -c "call LoadSessionT('$VIMSESSION','$VIMWINDOWS','e','split')"
                               ;;
                            c) vim -c "call LoadSessionT('$VIMSESSION','$VIMWINDOWS','e','split | split')"
                               ;;
                            *) vim -c "call LoadSessionT('$VIMSESSION','$VIMWINDOWS','e','$OPTARG')"
                               ;;
                        esac
               exit 0
               ;;
            m) vim -c MRU
               exit 0
               ;;
            t) vim -c "call LoadSessionT()"
               exit 0
               ;;
            e) vim  $VIMSESSION $VIMWINDOWS
               exit 0
               ;;
            h) print "vit"
               print "  -D      open with pwd directory pane"
               print "  -S      open with snips directory pane"
               print "  -R      open random name file"
               print "  -K      open KSH snip file"
               print "  -A, -G  open AWK snip file"
               print "  -a      side/side window layout"
               print "  -b      up/down window layout"
               print "  -c      up/mid/down window layout"
               print "  -e      Edit ./.vimsession ./.vimwindows"
               print "  -f      copy ./.vimsession to ./.vimwindows (and call vit)"
               print "  -m      Simple Mode with MRU"
               print "  -n      Toggle no-splits flag"
               print "  -h      Help"
               print "  -r      Remove ./.vimsession and ./.vimwindows"
               print "  -s      Simple Mode:Open in a single window"
               print "  -t      Only Windows Mode: Just open blank windows"
               print ""
               print "  -x  <layout>"
               print ""
               print "      layouts:"
               print "      a - side/side, b - up/down c - up/mid/down"
               print ""
               exit 0
               ;;
	esac
done

shift $(($OPTIND - 1))

if [ $# -eq 0 ]; then
          if [ "$VIMSPLIT" == "" ]; then 
              export VIMSPLIT=.vimsplit
          fi

          if [ -a "$VIMSPLIT" ] ; then
              vim -c "call LoadSessionT('$VIMSESSION','$VIMWINDOWS','e','')"
          else
              vim -c "call LoadSession()"
          fi
else
    vim $1 $2 $3 $4
fi

